### ISSUE TITLE
java_dev_appserver.cmd: InaccessibleObjectException: Unable to make static java.net.URLStreamHandler java.net.URL.getURLStreamHandler(java.lang.String) accessible: module java.base does not "opens java.net" to unnamed module 

### ISSUE THREAD

**Issue by gabrieljones** [GoogleCloudPlatform/appengine-java-standard#13]
```
PS C:\Users\gjones\IdeaProjects\AppEngine> C:\Users\gjones\AppData\Local\google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\bin\java_dev_appserver.cmd .\
Executing [C:\Users\gjones\scoop\apps\temurin17-jdk\current\bin\java, -Dfile.encoding=UTF-8, -classpath, C:\Users\gjones\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib\appengine-tools-api.jar, com.google.appengine.tools.development.DevAppServerMain, --property=kickstart.user.dir=C:\Users\gjones\IdeaProjects\AppEngine, --no_java_agent, --promote_yaml, C:\Users\gjones\IdeaProjects\AppEngine\.]
java.lang.RuntimeException: Unable to create a DevAppServer
        at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:378)
        at com.google.appengine.tools.development.DevAppServerFactory.createDevAppServer(DevAppServerFactory.java:310)
        at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:384)
        at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:58)
        at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:258)
        at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:249)
Caused by: java.lang.ExceptionInInitializerError
        at com.google.appengine.tools.development.DevAppServerImpl.<init>(DevAppServerImpl.java:135)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:363)
        ... 5 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make static java.net.URLStreamHandler java.net.URL.getURLStreamHandler(java.lang.String) accessible: module java.base does not "opens java.net" to unnamed module @6c64cb25
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.google.appengine.tools.development.StreamHandlerFactory.<clinit>(StreamHandlerFactory.java:52)
        ... 12 more
```

**Comment by ludoch** [comment]
The fix is to add the 3 flags:

--add-opens java.base/java.net=ALL-UNNAMED
--add-opens java.base/java.base/sun.net.www.protocol.http=ALL-UNNAMED
--add-opens java.base/java.base/sun.net.www.protocol.https=ALL-UNNAMED

in the kickstart java process... Making the change now.

**Comment by chetan-a3** [comment]
I am running appengine from eclipse, How we can add these in eclipse?
