### ISSUE TITLE
Application#compileJsps stopped working on Windows with 2.0.15

### ISSUE THREAD

**Issue by StefanIlchev** [GoogleCloudPlatform/appengine-java-standard#25]
After updating to gcloud 437.0.0 we started getting the following exception on Windows. It seems to have been introduced in [guava 32.0.0](https://github.com/google/guava/issues/6535) and fixed in [guava 32.0.1](https://github.com/google/guava/releases/tag/v32.0.1#:~:text=under%20Windows%2C%20which%20broke).

```
Unable to stage:
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
	at java.base/sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:134)
	at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:171)
	at java.base/java.nio.file.Files.createTempDirectory(Files.java:976)
	at com.google.appengine.repackaged.com.google.common.io.TempFileCreator$JavaNioCreator.createTempDir(TempFileCreator.java:102)
	at com.google.appengine.repackaged.com.google.common.io.Files.createTempDir(Files.java:439)
	at com.google.appengine.tools.admin.Application.compileJsps(Application.java:1229)
	at com.google.appengine.tools.admin.Application.populateStagingDirectory(Application.java:994)
	at com.google.appengine.tools.admin.Application.createStagingDirectory(Application.java:877)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:76)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplicationWithDefaultResourceLimits(AppAdminImpl.java:44)
	at com.google.appengine.tools.admin.AppCfg$StagingAction.execute(AppCfg.java:921)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:289)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:148)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:88)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:83)
com.google.appengine.tools.admin.AdminException: Unable to stage app: 'posix:permissions' not supported as initial attribute
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:82)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplicationWithDefaultResourceLimits(AppAdminImpl.java:44)
	at com.google.appengine.tools.admin.AppCfg$StagingAction.execute(AppCfg.java:921)
	at com.google.appengine.tools.admin.AppCfg.executeAction(AppCfg.java:289)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:148)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:88)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:83)
Caused by: java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
	at java.base/sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:134)
	at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:171)
	at java.base/java.nio.file.Files.createTempDirectory(Files.java:976)
	at com.google.appengine.repackaged.com.google.common.io.TempFileCreator$JavaNioCreator.createTempDir(TempFileCreator.java:102)
	at com.google.appengine.repackaged.com.google.common.io.Files.createTempDir(Files.java:439)
	at com.google.appengine.tools.admin.Application.compileJsps(Application.java:1229)
	at com.google.appengine.tools.admin.Application.populateStagingDirectory(Application.java:994)
	at com.google.appengine.tools.admin.Application.createStagingDirectory(Application.java:877)
	at com.google.appengine.tools.admin.AppAdminImpl.stageApplication(AppAdminImpl.java:76)
	... 6 more
```

**Comment by buzzgamesnews** [comment]
I get this bug too:

The error has been appearing since yesterday ( 06/28/2023 ) I did some research and realized that the error appears after the *.jsp module scans the appengineStage files:

_Beginning interaction for module default...
0% Scanning for jsp files.
0% Compiling jsp files.
Unable to stage app: 'posix:permissions' not supported as initial attribute_

After I tried to remove all *.jsp files and appengineStage was successful without errors, but *.jsp files are part of the project, what can I do ?
It doesn't matter what is in these files, the error appears even if you put an empty *.jsp file in the directory webapp.

**Comment by ludoch** [comment]
Thanks for the report.

We will upgrade to the newest guava, meanwhile, pin to the previous Cloud
CLI,

Ludo

**Comment by buzzgamesnews** [comment]
Thank you very much, I'm waiting, the process is stopped, I can't deploy the application to Google cloud

**Comment by Ihernandezpi** [comment]
The same issue! Waiting for the update 💯

**Comment by Emperorlou** [comment]
@ludoch I tried downgrading to 436 but the same issue seems to occur. I even tried a really old version (copied the filestructure over to a different computer that was running 2xx) and it still happened. There must be some cached file somewhere. I'll try wiping all the cache/build folders and see if that helps but if not I might be at a loss.

**Comment by ludoch** [comment]
How did you move back to version 436?
i.e: are you using the Maven or Gradle plugin and what is the plugin configuration? Or are you using the cloud CLI in command line mode? The plugins have their own version of the Cloud CLI tool (not the same one installed in a terminal), so need to be configure the plugin  to point the an older one, like in pom.xml:
```
<cloudSdkVersion> 436.0.0</cloudSdkVersion>
```
See https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md

Also, since next week is 4rth of July US break, I do not expect a Cloud CLI release before the week after.

**Comment by StefanIlchev** [comment]
**Notes: **
* The issue was introduced in gcloud `437.0.0` and occurs only on Windows if you have JSPs.
* The issue does not occur on Linux regardless of whether you have JSPs.
* I have not tried macOS but a quick web search shows that it like Linux is POSIX-compliant so the issue should not occur.
* To work around this issue on Windows you could use an older version of gcloud e.g., `436.0.0`. Here is an example of how to do that in a [Gradle](https://gradle.org/) build script with [appengine-gradle-plugin](https://cloud.google.com/appengine/docs/legacy/standard/java/gradle-reference#global_properties):

```gradle
appengine {

	tools {
		cloudSdkVersion = '436.0.0'
	}
}
```

**Comment by buzzgamesnews** [comment]
> **Notes:**
> 
> * The issue was introduced in gcloud `437.0.0` and occurs only on Windows if you have JSPs.
> * The issue does not occur on Linux regardless of whether you have JSPs.
> * I have not tried macOS but a quick web search shows that it like Linux is POSIX-compliant so the issue should not occur.
> * To work around this issue on Windows you could use an older version of gcloud e.g., `436.0.0`. Here is an example of how to do that in a [Gradle](https://gradle.org/) build script with [appengine-gradle-plugin](https://cloud.google.com/appengine/docs/legacy/standard/java/gradle-reference#global_properties):
> 
> ```groovy-gradle
> appengine {
> 
> 	tools {
> 		cloudSdkVersion = '436.0.0'
> 	}
> }
> ```

Thx. good workaround. I try from CLI gcloud components update --version=435.0.0 but it dont work

**Comment by Emperorlou** [comment]
> **Notes:**
> * The issue was introduced in gcloud `437.0.0` and occurs only on Windows if you have JSPs.
> * The issue does not occur on Linux regardless of whether you have JSPs.
> * I have not tried macOS but a quick web search shows that it like Linux is POSIX-compliant so the issue should not occur.
> * To work around this issue on Windows you could use an older version of gcloud e.g., `436.0.0`. Here is an example of how to do that in a [Gradle](https://gradle.org/) build script with [appengine-gradle-plugin](https://cloud.google.com/appengine/docs/legacy/standard/java/gradle-reference#global_properties):
> 
> ```gradle
> appengine {
> 
> 	tools {
> 		cloudSdkVersion = '436.0.0'
> 	}
> }
> ```
> 

Good call! This worked for me, thanks! I suppose the lack of version control in my gradle file is also what ultimately caused the biggest problems.

**Comment by ludoch** [comment]
Cloud SDK CLI has been updated and will be released next Tuesday.

**Comment by TheCloudGate** [comment]
Hi,

Going back to previous version is not working as expected.

@ludoch when you mention next Tuesday, are you talking about 18th July? 

https://cloud.google.com/sdk/docs/release-notes

Thanks.

**Comment by ludoch** [comment]
Going back to version 436.0.0 should work (see above thread for Maven or Gradle plugins)

Fix will be in version of the week of 18th July

**Comment by iamthefaker** [comment]
I'm getting the same error, but I'm not sure if it's the same issue.
I am using Maven not Gradle, and I am using AppEngine SDK not Cloud SDK.
I've tried endless different versions of things, but I still get this same error.
_0% Scanning for jsp files.
0% Compiling jsp files.
Unable to stage app: 'posix:permissions' not supported as initial attribute_

**Comment by Ciberdim** [comment]
Update to the new version (438.0.0), the bug is still there and it prevents users from deploying. Google must be the only business willing to leave such a bug unfixed for this long. I am seriously considering moving to Azure or AWS; this is outrageous.

**Comment by ludoch** [comment]
The fix is in today's 439.0.0 (2023-07-18)  build.
