### ISSUE TITLE
Getting "Request failed: Unexpected exception from servlet: java.lang.reflect.InvocationTargetException" in new deployed GAE apps

### ISSUE THREAD

**Issue by TheCloudGate** [GoogleCloudPlatform/appengine-java-standard#57]
Hello, we are getting the `Request failed: Unexpected exception from servlet: java.lang.reflect.InvocationTargetException` error in the new versions that we are deploying. It's a Java 17 maven project. This issue is happening to us since the new version of Google Cloud CLI has been released (version 447.0.0), and in that releases notes in "App Engine" section is indicated "Updated the Java SDK to version 2.0.19 build from the open source project https://github.com/GoogleCloudPlatform/appengine-java-standard/releases/tag/v2.0.19"

The logs are returning this: 
```shell
"Failed startup of context c.g.a.r.j.AppEngineWebAppContext@43733fa1{/,file:///workspace/,UNAVAILABLE}{/workspace}
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:86)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:74)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:399)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1412)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at com.google.apphosting.runtime.jetty94.AppEngineWebAppContext.doStart(AppEngineWebAppContext.java:218)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at com.google.apphosting.runtime.jetty94.AppVersionHandlerFactory.doCreateHandler(AppVersionHandlerFactory.java:207)
	at com.google.apphosting.runtime.jetty94.AppVersionHandlerFactory.createHandler(AppVersionHandlerFactory.java:125)
	at com.google.apphosting.runtime.jetty94.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:82)
	at com.google.apphosting.runtime.jetty94.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:177)
	at com.google.apphosting.runtime.RequestRunner.dispatchServletRequest(RequestRunner.java:264)
	at com.google.apphosting.runtime.RequestRunner.dispatchRequest(RequestRunner.java:229)
	at com.google.apphosting.runtime.RequestRunner.run(RequestRunner.java:194)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:91)
	at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
	at org.eclipse.jetty.apache.jsp.JettyJasperInitializer.<clinit>(JettyJasperInitializer.java:39)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.<init>(ContainerInitializer.java:62)
	at org.eclipse.jetty.quickstart.QuickStartDescriptorProcessor.visitContextParam(QuickStartDescriptorProcessor.java:187)
	... 22 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/log/Log
	at org.eclipse.jetty.apache.jsp.JuliLog.<init>(JuliLog.java:33)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 34 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.log.Log
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at com.google.apphosting.runtime.ApplicationClassLoader.findClass(ApplicationClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 41 more
``` 
I don't know if it can be something related to my `pom.xml` or `web.xml` files but the thing is that we started getting this error since the new version of Google Client (v 447.0.0) releases and we didn't change anything. 

If you need some more information about anything please, just let us know and we will provide it as soon as possible. Thank you!

**Comment by rodteixo** [comment]
Hello. I am getting exactly same problem.

Google CLI has been updated automatically in my eclipse setup, now I cannot make any deployment to work.

I just get this message: Request failed: Unexpected exception from servlet: java.lang.reflect.InvocationTargetException

And nothing else... 

I just made a deployment if you want to try: 
https://397-dot-horariofacil-hrd.appspot.com/

Please, someone on google team help with this asap.

Thank you very much in advance,
[],
Rodrigo.

**Comment by TheCloudGate** [comment]
Hello @rodteixo , we rencently fixed this issue with help of the Google Support Team. You just have to add the following dependency to your `pom.xml` file or it's equivalence if your using Gradle instead of Maven:

```
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-util</artifactId>
    <version>9.4.52.v20230823</version>
</dependency>
```

We asked for the exacts reasons of why is this working but for the moment we haven't got response from Google Support Team. Please try this and let us know If it is working for you.

Regards, The Cloud Gate Team

**Comment by rodteixo** [comment]
@TheCloudGate 

Thank you very much. 
Adding that dependency to my pom solved the problem. It worked !
