### ISSUE TITLE
E10 allinone_jakarta test emits errors

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-standard#70]
While the test execution is green (https://github.com/GoogleCloudPlatform/appengine-java-standard/actions/runs/6561983579/job/17822942466) when I open the test log, and go to the end, I see 2 new types of errors happening only in the jarkata EE 10 tests mode:

```
Error: Exception in thread "Thread-14" java.lang.RuntimeException: java.io.IOException: Stream closed
	at com.google.appengine.tools.development.DevAppServerTestBase$OutputPump.run(DevAppServerTestBase.java:227)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:188)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:343)
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:405)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:329)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:372)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:215)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:169)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:188)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:160)
	at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:370)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:347)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:436)
	at com.google.appengine.tools.development.DevAppServerTestBase$OutputPump.run(DevAppServerTestBase.java:220)
```

and

```
Oct 18, 2023 2:25:50 PM allinone.MainServlet emit
INFO: Cache misses: 0
2023-10-18 14:25:50.786:WARN :oejes.ServletChannel:qtp1003752023-25: unknown request
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.server.Request.getAttribute(String)" because "request" is null
	at org.eclipse.jetty.server.Request.getAuthenticationState(Request.java:912)
	at org.eclipse.jetty.security.AuthenticationState.getAuthenticationState(AuthenticationState.java:45)
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getAuthentication(ServletApiRequest.java:128)
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getUndeferredAuthentication(ServletApiRequest.java:133)
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getUserPrincipal(ServletApiRequest.java:345)
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getRemoteUser(ServletApiRequest.java:324)
	at com.google.appengine.tools.development.jetty.ee10.JettyContainerService.onComplete(JettyContainerService.java:702)
	at com.google.appengine.tools.development.jetty.ee10.JettyContainerService$ApiProxyHandler.lambda$handle$0(JettyContainerService.java:636)
	at org.eclipse.jetty.util.Callback$5.completed(Callback.java:242)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:420)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.onCompleted(ServletChannel.java:823)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:481)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:693)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:713)
	at com.google.appengine.tools.development.jetty.ee10.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:637)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:812)
	at org.eclipse.jetty.server.Server.handle(Server.java:177)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:649)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:471)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2023-10-18 14:25:50.787:WARN :oejs.Response:qtp1003752023-25: writeError: status=500, message=java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.ee10.servlet.ServletContextResponse.isCommitted()" because the return value of "org.eclipse.jetty.ee10.servlet.ServletChannel.getServletContextResponse()" is null, response=org.eclipse.jetty.ee10.servlet.ServletContextResponse@5f145073
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.ee10.servlet.ServletContextResponse.isCommitted()" because the return value of "org.eclipse.jetty.ee10.servlet.ServletChannel.getServletContextResponse()" is null
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.isResponseCommitted(ServletChannelState.java:311)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.isCommitted(ServletChannel.java:834)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handleException(ServletChannel.java:716)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:641)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:693)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:713)
	at com.google.appengine.tools.development.jetty.ee10.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:637)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:812)
	at org.eclipse.jetty.server.Server.handle(Server.java:177)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:649)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:471)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Oct 18, 2023 2:25:50 PM allinone.MainServlet emit

```

Not sure why...

**Comment by lachlan-roberts** [comment]
This used to use a `HttpChannel.Listener` which does not exist anymore, and now it is wrapping the callback to notify the onComplete method. The problem is by the time the callback is succeeded the request has been recycled so methods on the request like `getUserPrincipal` are throwing errors. This is then triggering the other NPE from `isCommitted()`. 

We are looking into adding some additional changes to Jetty 12 so that we can get a better interception point where we still have access to the servlet request methods.

**Comment by gregw** [comment]
@lachlan-roberts Have a look at https://github.com/jetty/jetty.project/pull/10801.   Rather than be more creative about intercepting the completion event, this PR retains the association on the `ServletChannel` until it is reused.
