### ISSUE TITLE
SpringBoot 3.2 M3 and Jetty12 EE10 GAE as a war app.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-standard#73]
Sample code is at: https://github.com/ludoch/appengine-spring-boot

We can test to see what is not working in local devappserver:

 with running the  ./sdk_assembly/target/appengine-java-sdk/bin/dev_appserver.sh <appPath> script locally built

Main page / does not really work (stuck) same for /aliens handler

Notice the version = 6 in https://github.com/ludoch/appengine-spring-boot/blob/master/src/main/webapp/WEB-INF/web.xml#L2
This is the trigger for using EE10 with GAE Jetty12.

**Comment by ludoch** [comment]
So I think local server is working with the recent change, but then tried to execute the Prod runtime (locally with local emulator) and got this error on the staged application:


```
[stderr] Nov 20, 2023 10:03:07 PM com.google.apphosting.runtime.jetty.proxy.JettyHttpProxy newServer
[stderr] INFO: Starting Jetty http server for Java runtime proxy.
[stderr] Nov 20, 2023 10:03:07 PM org.eclipse.jetty.server.Server doStart
[stderr] INFO: jetty-12.0.3; built: 2023-10-27T03:25:22.284Z; git: a873259fd5af141dedaa6c7fa8fe8fbdedce0d61; jvm 17.0.3+7
[stderr] Nov 20, 2023 10:03:07 PM org.eclipse.jetty.server.AbstractConnector doStart
[stderr] INFO: Started JettyServerConnectorWithReusePort@6d025197{HTTP/1.1, (http/1.1)}{0.0.0.0:58736}
[stderr] Nov 20, 2023 10:03:07 PM org.eclipse.jetty.server.Server doStart
[stderr] INFO: Started oejs.Server@558bdf1f{STARTING}[12.0.3,sto=0] @1648ms
[stderr] Nov 20, 2023 10:03:07 PM org.eclipse.jetty.server.Server doStart
[stderr] INFO: jetty-12.0.3; built: 2023-10-27T03:25:22.284Z; git: a873259fd5af141dedaa6c7fa8fe8fbdedce0d61; jvm 17.0.3+7
[stderr] Nov 20, 2023 10:03:07 PM org.eclipse.jetty.server.AbstractConnector doStart
[stderr] INFO: Started @6eb2384f{RPC, (rpc)}
[stderr] Nov 20, 2023 10:03:07 PM org.eclipse.jetty.server.Server doStart
[stderr] INFO: Started cgarj.JettyServletEngineAdapter$@32a68f4f{STARTING}[12.0.3,sto=0] @1652ms
[stderr] Nov 20, 2023 10:03:07 PM com.google.apphosting.runtime.JavaRuntime$RpcRunnable startServer
[stderr] INFO: Beginning accept loop.
[stderr] Nov 20, 2023 10:03:09 PM com.google.apphosting.runtime.RequestManager getAdjustedRpcDeadline
[stderr] WARNING: Did not receive enough RPC information to calculate adjusted deadline: com.google.apphosting.runtime.jetty.proxy.JettyHttpProxy$LocalRpcContext@b4950a2
[stderr] Nov 20, 2023 10:03:09 PM com.google.apphosting.runtime.RequestManager getAdjustedRpcDeadline
[stderr] WARNING: Did not receive enough RPC information to calculate adjusted deadline: com.google.apphosting.runtime.jetty.proxy.JettyHttpProxy$LocalRpcContext@b4950a2
[stderr] Nov 20, 2023 10:03:09 PM com.google.apphosting.runtime.RequestManager startRequest
[stderr] INFO: Beginning request 0000000000000001 remaining millis : 60000
[stderr] Nov 20, 2023 10:03:10 PM org.eclipse.jetty.ee10.webapp.WebAppContext doStart
[stderr] WARNING: Failed startup of context cgarje10.AppEngineWebAppContext@74c0c26{ROOT,/,b=[file:///Users/ludo/ee10/spring/appengine-spring-boot/target/appengine-staging/, jar:file:///Users/ludo/ee10/spring/appengine-spring-boot/target/appengine-staging/WEB-INF/lib/jquery-3.7.1.jar!/META-INF/resources/, jar:file:///Users/ludo/ee10/spring/appengine-spring-boot/target/appengine-staging/WEB-INF/lib/bootstrap-5.3.2.jar!/META-INF/resources/],a=STOPPED,h=oeje10s.SessionHandler@31a6509b{STOPPED}}{/Users/ludo/ee10/spring/appengine-spring-boot/target/appengine-staging}
[stderr] java.lang.reflect.InvocationTargetException
[stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[stderr] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[stderr] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[stderr] 	at org.eclipse.jetty.ee10.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:81)
[stderr] 	at org.eclipse.jetty.ee10.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:69)
[stderr] 	at org.eclipse.jetty.ee10.webapp.MetaData.resolve(MetaData.java:475)
[stderr] 	at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext(WebAppContext.java:1222)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.AppEngineWebAppContext.startContext(AppEngineWebAppContext.java:286)
[stderr] 	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1041)
[stderr] 	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1206)
[stderr] 	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1038)
[stderr] 	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:496)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.AppEngineWebAppContext.doStart(AppEngineWebAppContext.java:232)
[stderr] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.EE10AppVersionHandlerFactory.doCreateHandler(EE10AppVersionHandlerFactory.java:213)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.EE10AppVersionHandlerFactory.createHandler(EE10AppVersionHandlerFactory.java:108)
[stderr] 	at com.google.apphosting.runtime.jetty.AppVersionHandler.ensureHandler(AppVersionHandler.java:79)
[stderr] 	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:201)
[stderr] 	at com.google.apphosting.runtime.RequestRunner.dispatchServletRequest(RequestRunner.java:262)
[stderr] 	at com.google.apphosting.runtime.RequestRunner.dispatchRequest(RequestRunner.java:227)
[stderr] 	at com.google.apphosting.runtime.RequestRunner.run(RequestRunner.java:193)
[stderr] 	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:273)
[stderr] 	at java.base/java.lang.Thread.run(Thread.java:833)
[stderr] Caused by: java.lang.IllegalArgumentException: Base resource cannot be combined!
[stderr] 	at org.eclipse.jetty.util.resource.AttributeNormalizer.<init>(AttributeNormalizer.java:210)
[stderr] 	at org.eclipse.jetty.ee10.quickstart.QuickStartDescriptorProcessor.visitContextParam(QuickStartDescriptorProcessor.java:157)
[stderr] 	... 24 more
[stderr] 
[stderr] Nov 20, 2023 10:03:10 PM com.google.apphosting.runtime.RequestRunner handleException
[stderr] WARNING: Uncaught exception from servlet
[stderr] java.lang.reflect.InvocationTargetException
[stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[stderr] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[stderr] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[stderr] 	at org.eclipse.jetty.ee10.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:81)
[stderr] 	at org.eclipse.jetty.ee10.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:69)
[stderr] 	at org.eclipse.jetty.ee10.webapp.MetaData.resolve(MetaData.java:475)
[stderr] 	at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext(WebAppContext.java:1222)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.AppEngineWebAppContext.startContext(AppEngineWebAppContext.java:286)
[stderr] 	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1041)
[stderr] 	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1206)
[stderr] 	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1038)
[stderr] 	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:496)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.AppEngineWebAppContext.doStart(AppEngineWebAppContext.java:232)
[stderr] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.EE10AppVersionHandlerFactory.doCreateHandler(EE10AppVersionHandlerFactory.java:213)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.EE10AppVersionHandlerFactory.createHandler(EE10AppVersionHandlerFactory.java:108)
[stderr] 	at com.google.apphosting.runtime.jetty.AppVersionHandler.ensureHandler(AppVersionHandler.java:79)
[stderr] 	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:201)
[stderr] 	at com.google.apphosting.runtime.RequestRunner.dispatchServletRequest(RequestRunner.java:262)
[stderr] 	at com.google.apphosting.runtime.RequestRunner.dispatchRequest(RequestRunner.java:227)
[stderr] 	at com.google.apphosting.runtime.RequestRunner.run(RequestRunner.java:193)
[stderr] 	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:273)
[stderr] 	at java.base/java.lang.Thread.run(Thread.java:833)
[stderr] Caused by: java.lang.IllegalArgumentException: Base resource cannot be combined!
[stderr] 	at org.eclipse.jetty.util.resource.AttributeNormalizer.<init>(AttributeNormalizer.java:210)
[stderr] 	at org.eclipse.jetty.ee10.quickstart.QuickStartDescriptorProcessor.visitContextParam(QuickStartDescriptorProcessor.java:157)
[stderr] 	... 24 more
[stderr] 
[stderr] Nov 20, 2023 10:03:10 PM com.google.apphosting.runtime.RequestRunner setFailure
[stderr] WARNING: Runtime failed: APP_FAILURE, Unexpected exception from servlet: java.lang.reflect.InvocationTargetException
[stderr] Nov 20, 2023 10:03:10 PM com.google.apphosting.runtime.RequestManager finishRequest
[stderr] INFO: Stopped timer for request 0000000000000001 0.365 CPU / 0.414 wallclock (88.2%), 759.134 Mcycles@1.0GHz[0.389 hotspot, 0.005 GC]
[stderr] Nov 20, 2023 10:03:10 PM com.google.apphosting.runtime.jetty.proxy.JettyHttpProxy$ForwardingHandler getUpResponse
[stderr] SEVERE: Uncaught exception from servlet
[stderr] java.lang.reflect.InvocationTargetException
[stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[stderr] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[stderr] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[stderr] 	at org.eclipse.jetty.ee10.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:81)
[stderr] 	at org.eclipse.jetty.ee10.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:69)
[stderr] 	at org.eclipse.jetty.ee10.webapp.MetaData.resolve(MetaData.java:475)
[stderr] 	at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext(WebAppContext.java:1222)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.AppEngineWebAppContext.startContext(AppEngineWebAppContext.java:286)
[stderr] 	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1041)
[stderr] 	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1206)
[stderr] 	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1038)
[stderr] 	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:496)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.AppEngineWebAppContext.doStart(AppEngineWebAppContext.java:232)
[stderr] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.EE10AppVersionHandlerFactory.doCreateHandler(EE10AppVersionHandlerFactory.java:213)
[stderr] 	at com.google.apphosting.runtime.jetty.ee10.EE10AppVersionHandlerFactory.createHandler(EE10AppVersionHandlerFactory.java:108)
[stderr] 	at com.google.apphosting.runtime.jetty.AppVersionHandler.ensureHandler(AppVersionHandler.java:79)
[stderr] 	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:201)
[stderr] 	at com.google.apphosting.runtime.RequestRunner.dispatchServletRequest(RequestRunner.java:262)
[stderr] 	at com.google.apphosting.runtime.RequestRunner.dispatchRequest(RequestRunner.java:227)
[stderr] 	at com.google.apphosting.runtime.RequestRunner.run(RequestRunner.java:193)
[stderr] 	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:273)
[stderr] 	at java.base/java.lang.Thread.run(Thread.java:833)
[stderr] Caused by: java.lang.IllegalArgumentException: Base resource cannot be combined!
[stderr] 	at org.eclipse.jetty.util.resource.AttributeNormalizer.<init>(AttributeNormalizer.java:210)
[stderr] 	at org.eclipse.jetty.ee10.quickstart.QuickStartDescriptorProcessor.visitContextParam(QuickStartDescriptorProcessor.java:157)

```

**Comment by ludoch** [comment]
The min-quickstart-web.xml file generated during stage quickstart process is:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" metadata-complete="false" version="6.0" xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_6_0.xsd">
      
    <display-name>ROOT</display-name>
      
    <context-param>
            
        <param-name>org.eclipse.jetty.containerInitializers</param-name>
            
        <param-value><![CDATA[
    "ContainerInitializer{org.eclipse.jetty.ee10.apache.jsp.JettyJasperInitializer,interested=[],applicable=[],annotated=[]}",
    "ContainerInitializer{org.springframework.web.SpringServletContainerInitializer,interested=[org.springframework.boot.web.servlet.support.SpringBootServletInitializer, org.springframework.web.context.AbstractContextLoaderInitializer, org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration$JerseyWebApplicationInitializer, org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer, org.springframework.web.server.adapter.AbstractReactiveWebInitializer, org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer, com.github.michaeltecourt.appengine.server.SampleSpringBootApplication, org.springframework.web.servlet.support.AbstractDispatcherServletInitializer],applicable=[],annotated=[]}",
    "ContainerInitializer{ch.qos.logback.classic.servlet.LogbackServletContainerInitializer,interested=[],applicable=[],annotated=[]}"]]></param-value>
          
    </context-param>
      
    <context-param>
            
        <param-name>org.eclipse.jetty.tlds</param-name>
            
        <param-value><![CDATA[
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/permittedTaglibs.tld",
    "jar:${WAR.uri}/WEB-INF/lib/spring-webmvc-6.1.0-M5.jar!/META-INF/spring.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/x-1_0.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql-1_0.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/x-1_0-rt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x-1_1.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/scriptfree-1_1.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x-1_0-rt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_0-rt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/permittedTaglibs.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x-1_0.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql-1_0-rt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_0.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_0-rt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_0-rt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_0.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_1.tld",
    "jar:${WAR.uri}/WEB-INF/lib/spring-webmvc-6.1.0-M5.jar!/META-INF/spring-form.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/x.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/scriptfree.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/permittedTaglibs-1_1.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/scriptfree.tld",
    "jar:${WAR.uri}/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0-rt.tld",
    "jar:${WAR.uri}/WEB-INF/lib/org.glassfish.web.jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_0.tld"]]></param-value>
          
    </context-param>
      
    <context-param>
            
        <param-name>org.eclipse.jetty.resources</param-name>
            
        <param-value><![CDATA[
    "jar:${WAR.uri}/WEB-INF/lib/jquery-3.7.1.jar!/META-INF/resources/",
    "jar:${WAR.uri}/WEB-INF/lib/bootstrap-5.3.2.jar!/META-INF/resources/"]]></param-value>
          
    </context-param>
      
    <context-param>
            
        <param-name>org.eclipse.jetty.originAttribute</param-name>
            
        <param-value>origin</param-value>
          
    </context-param>
      
    <servlet>

```
